/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import static carrentalsystem.Customer_ViewBooking.customerid_value;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bende
 */
public class Admin_ViewCustomerBooking extends javax.swing.JFrame {

    /**
     * Creates new form Admin_ViewCustomerBooking
     */
    public Admin_ViewCustomerBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print_receipt_page = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cus_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cus_booking_history = new javax.swing.JTable();
        display_id = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Admin View Customer Booking");

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Customer Name:");

        cus_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cus_booking_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Customer Name", "Car ID", "Car Name", "Rent Price", "Booking Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cus_booking_history);

        display_id.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        display_id.setText("Print Receipt");
        display_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout print_receipt_pageLayout = new javax.swing.GroupLayout(print_receipt_page);
        print_receipt_page.setLayout(print_receipt_pageLayout);
        print_receipt_pageLayout.setHorizontalGroup(
            print_receipt_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_receipt_pageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(print_receipt_pageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_receipt_pageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(print_receipt_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_receipt_pageLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69)
                        .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, print_receipt_pageLayout.createSequentialGroup()
                        .addComponent(display_id, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
        );
        print_receipt_pageLayout.setVerticalGroup(
            print_receipt_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(print_receipt_pageLayout.createSequentialGroup()
                .addGroup(print_receipt_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(print_receipt_pageLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(print_receipt_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cus_name, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(print_receipt_pageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(display_id, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(print_receipt_page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(print_receipt_page, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        AdminClass admin = new AdminClass();
        admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void display_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_idActionPerformed
        String get_cus_name = cus_name.getText();
        String cus_id = "";
        int action=-1;
        File view_booking_details = new File("Booking.txt");
        try {
            BufferedReader read_booking_details = new BufferedReader(new FileReader(view_booking_details));
            String each_book_lines = read_booking_details.readLine();
            DefaultTableModel show_booking_details = (DefaultTableModel)cus_booking_history.getModel();
            Object[] booking_info = read_booking_details.lines().toArray();

            
            for(int i=0; i<booking_info.length; i++){
                
                String book_line = booking_info[i].toString();
                //System.out.println(car_line);
                String get_all_data[] = book_line.split("\t");

                if(get_all_data[2].equals(get_cus_name)){
                    action = 1;
                    //get the id from name
                    cus_id = get_all_data[1];
                    show_booking_details.addRow(get_all_data);
                    
                    display_id.setEnabled(false);
                    //show_booking_details.addRow(get_all_data);
                    
                }else{

                }
                
            }
            //hiding the customer ID colunmn & customer name
            cus_booking_history.getColumnModel().getColumn(1).setMinWidth(0);
            cus_booking_history.getColumnModel().getColumn(1).setMaxWidth(0);
            cus_booking_history.getColumnModel().getColumn(2).setMinWidth(0);
            cus_booking_history.getColumnModel().getColumn(2).setMaxWidth(0);
            
            if(action == 1){
                JOptionPane.showMessageDialog(this, "The Customer ID is: " + cus_id, "Information Message", JOptionPane.INFORMATION_MESSAGE);
                //Allow the admin to print out receipt
                 PrinterJob print_cus_booking_history = PrinterJob.getPrinterJob();
        
                 print_cus_booking_history.setPrintable(new Printable(){
                 //graphics-the content of the page
                 //format - size and orientation (X & Y)
                 //page_number - number of the page to print
                  public int print(Graphics graphics,PageFormat format,int page_number){
                
                
                 Graphics2D cus_page = (Graphics2D)graphics;
                 //create a 2D scale in the PDF(after print)
                  //X and Y axis
                  cus_page.scale(0.7, 0.7);
                  cus_page.translate(format.getImageableX(), format.getImageableY());
                
                
                  print_receipt_page.print(cus_page);
                  return Printable.PAGE_EXISTS;
                     }
                  });
                     boolean allow_print = print_cus_booking_history.printDialog();
                    //if click print
                if(allow_print){
                try {
                print_cus_booking_history.print();
                } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(this, "Error Occur for Print, Please Try Again!", "Error Message", JOptionPane.ERROR_MESSAGE);
                }
            
        }
        //printing receipt end here
            }else{
                JOptionPane.showMessageDialog(this, "The Customer Name Not Found!", "Information Message", JOptionPane.WARNING_MESSAGE);
                
            }
            
            
        
        

        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_display_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_ViewCustomerBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_ViewCustomerBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTable cus_booking_history;
    private javax.swing.JTextField cus_name;
    private javax.swing.JButton display_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel print_receipt_page;
    // End of variables declaration//GEN-END:variables
}
