/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import Class.Booking;
import Class.Vehicle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Crosswind Cheah
 */
public class Customer_ReturnCar extends javax.swing.JFrame {
    public int JOP = 0;
    
    public static int jopvalue;
    public static String customerid_value;
    
    /**
     * Creates new form Customer_ReturnCar
     */
    public Customer_ReturnCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        return_car_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        carid_textfield = new javax.swing.JTextField();
        returncar_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bookingid_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        return_car_lbl.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        return_car_lbl.setText("Customer Return Car");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Car ID:");

        carid_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carid_textfieldActionPerformed(evt);
            }
        });

        returncar_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returncar_btn.setText("Return");
        returncar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returncar_btnActionPerformed(evt);
            }
        });

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Booking ID:");

        bookingid_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookingid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingid_textfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addGap(40, 40, 40)
                            .addComponent(carid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(165, 165, 165)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(40, 40, 40)
                        .addComponent(bookingid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(return_car_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(205, 205, 205)
                            .addComponent(returncar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carid_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(return_car_lbl)
                    .addGap(165, 165, 165)
                    .addComponent(returncar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returncar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returncar_btnActionPerformed
        
        
        if( bookingid_textfield.getText().length()<=0 || carid_textfield.getText().length()<=0){
            JOptionPane.showMessageDialog(this, "Please fill in the empty field", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        }else if(bookingid_textfield.getText().matches("[a-zA-Z]+") || carid_textfield.getText().matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(this, "Please enter a valid number", "Information Message", JOptionPane.INFORMATION_MESSAGE);
        
            
        }else{
        String bookingid_value = bookingid_textfield.getText();
        int int_book_id = Integer.parseInt(bookingid_value);
        String carid_value = carid_textfield.getText();
        int number = Integer.parseInt(carid_value);
        String status = "0";
        Booking return_car = new Booking(int_book_id,carid_value,customerid_value,status); 
        
        
        try {
            return_car.returncar();
            switch (jopvalue) {
                case 1 -> {
                    JOptionPane.showMessageDialog(this, "Returned Successfully, Have a Nice Day", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println(JOP);
                    jopvalue = 0;
                    CustomerClass customerpage = new CustomerClass();
                    customerpage.setVisible(true);
                    dispose();
                }
                case 2 -> //car status not approved
                    
                    JOptionPane.showMessageDialog(this, "Car is not available to return", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                case 0 -> JOptionPane.showMessageDialog(this, "Record not found", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                default -> JOptionPane.showMessageDialog(this, "Record unavailable", "Information Message", JOptionPane.INFORMATION_MESSAGE);
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(BookingConfirmation.class.getName()).log(Level.SEVERE, null, ex);
        }
        //returncar_btn.setEnabled(false);
        
        }
    }//GEN-LAST:event_returncar_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        CustomerClass back = new CustomerClass();
        back.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void carid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carid_textfieldActionPerformed

    private void bookingid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingid_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_ReturnCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_ReturnCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField bookingid_textfield;
    private javax.swing.JTextField carid_textfield;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel return_car_lbl;
    private javax.swing.JButton returncar_btn;
    // End of variables declaration//GEN-END:variables
}
