/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import static carrentalsystem.Customer_login.get_customerid;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author Crosswind Cheah
 */
public class CustomerClass extends javax.swing.JFrame {
    
    String cusername;
    
    /**
     * Creates new form CustomerClass
     */
    public CustomerClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cus_panel_lbl = new javax.swing.JLabel();
        select_function_lbl = new javax.swing.JLabel();
        SearchCarBtn = new javax.swing.JButton();
        ViewBookingHistoryBtn = new javax.swing.JButton();
        ReturnCarBtn = new javax.swing.JButton();
        ViewPaymentBtn = new javax.swing.JButton();
        EditProfileBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(796, 390));

        cus_panel_lbl.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        cus_panel_lbl.setText("Customer Panel");

        select_function_lbl.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        select_function_lbl.setText("Please Select Below Function");

        SearchCarBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        SearchCarBtn.setText("Book a Car");
        SearchCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCarBtnActionPerformed(evt);
            }
        });

        ViewBookingHistoryBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ViewBookingHistoryBtn.setText("View Booking");
        ViewBookingHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingHistoryBtnActionPerformed(evt);
            }
        });

        ReturnCarBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ReturnCarBtn.setText("Return Car");
        ReturnCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCarBtnActionPerformed(evt);
            }
        });

        ViewPaymentBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ViewPaymentBtn.setText("View Payment");
        ViewPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPaymentBtnActionPerformed(evt);
            }
        });

        EditProfileBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        EditProfileBtn.setText("Edit Profile");
        EditProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileBtnActionPerformed(evt);
            }
        });

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(select_function_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ViewBookingHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SearchCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(110, 110, 110)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ReturnCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ViewPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(cus_panel_lbl)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(cus_panel_lbl)
                .addGap(33, 33, 33)
                .addComponent(select_function_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewBookingHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCarBtnActionPerformed
        // TODO add your handling code here:
        
        
        Customer_booking booking = new Customer_booking();
                booking.setVisible(true);
                
//                File read_car_detailss = new File("Car.txt");
//        try {
//            BufferedReader read_cars = new BufferedReader(new FileReader(read_car_detailss));
//            String each_car_lines = read_cars.readLine();
//            //System.out.println(each_car_line);
//            //display in table form (car details)
//                        //DefaultTableModel show_car_details = (DefaultTableModel)car_table.getModel();
//
//                 
//            
//            Object[] car_info = read_cars.lines().toArray();
//
//
//            for(int i=0; i<car_info.length; i++){
//                String car_line = car_info[i].toString();
//                System.out.println(car_line);
//                String get_all_data[] = car_line.split("\t");
//
//                
//                //show_car_detailss.addRow(get_all_data);
//            }
//        
//        
//        } catch (FileNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            java.util.logging.Logger.getLogger(ViewCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
       
                dispose();
    }//GEN-LAST:event_SearchCarBtnActionPerformed

    private void ViewBookingHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingHistoryBtnActionPerformed
        // TODO add your handling code here:
        Customer_ViewBooking viewbooking = new Customer_ViewBooking();
        viewbooking.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewBookingHistoryBtnActionPerformed

    private void ReturnCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCarBtnActionPerformed
        // TODO add your handling code here:
        Customer_ReturnCar returncar = new Customer_ReturnCar();
        returncar.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnCarBtnActionPerformed

    private void ViewPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPaymentBtnActionPerformed
        // TODO add your handling code here:
        Customer_Payment viewPayment = new Customer_Payment();
        viewPayment.setVisible(true);
        dispose();
    }//GEN-LAST:event_ViewPaymentBtnActionPerformed

    private void EditProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileBtnActionPerformed
        // TODO add your handling code here:
        Customer_EditProfile edit = new Customer_EditProfile();
        edit.setVisible(true);
        dispose();
    }//GEN-LAST:event_EditProfileBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        MainClass main = new MainClass();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //System.out.println(cusername);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerClass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditProfileBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton ReturnCarBtn;
    private javax.swing.JButton SearchCarBtn;
    private javax.swing.JButton ViewBookingHistoryBtn;
    private javax.swing.JButton ViewPaymentBtn;
    private javax.swing.JLabel cus_panel_lbl;
    private javax.swing.JLabel select_function_lbl;
    // End of variables declaration//GEN-END:variables
}
