/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carrentalsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bende
 */
public class EditCar extends javax.swing.JFrame {

    /**
     * Creates new form EditCar
     */
    public EditCar() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search_textfield = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        details_selection = new javax.swing.JComboBox<>();
        changes_textfield = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        header.setText("Admin Edit Car");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Car Serial Number: ");

        search_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_textfieldKeyTyped(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        details_selection.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        details_selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Car_Brand", "Car_Model", "Car_Type", "Number_Plate", "Car_Gear", "Passenger_Occupancy", "Fuel_Type", "Travel_Distance", "Car_cc", "Manufacture_Year", "Serial_Number", "Engine_ID", "Engine_Type", "Car_HP", "Rent_Price" }));

        changes_textfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        changes_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                changes_textfieldKeyTyped(evt);
            }
        });

        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(header))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addComponent(details_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(changes_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(281, 281, 281)
                            .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(header))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(details_selection, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changes_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        String search_text = search_textfield.getText();
        int action = 0, line = 0;
        int get_changes_item=-1;
        try {          
            File car_file = new File("Car.txt");
            Scanner scan_data = new Scanner(car_file);
            ArrayList<String> array_car = new ArrayList<>();
            ArrayList<String> write_car = new ArrayList<>();
            
            while(scan_data.hasNextLine()){
                String each_line = scan_data.nextLine();
                 line = line + 1;
                
                String[] each_car_details = each_line.split("\n");
                String[] each_car_det = each_car_details[0].split("\t");
                
                //Get the seraial number of each car 
                String serial = each_car_det[11];

                //use for checking that line for Edit
                array_car.add(each_car_details[0]);

                
                if(search_text.equals(serial)){
                    //line = line + 1;
                    action = 1; 
                    //show that changes line
                    String update_text = changes_textfield.getText();
                    //get the selection number from combobox
                    get_changes_item = details_selection.getSelectedIndex();  
                    

                    String old_word = each_car_det[get_changes_item];
                    //System.out.println(line);
                    System.out.println(array_car.get(line));
                    String new_car_details = (array_car.get(line).replace(old_word, update_text));
                    //System.out.println(new_car_details);
                    //Crate write car for writing into Car.txt
                    write_car.add(new_car_details);
                    array_car.set(line, new_car_details);
                    

                }else{
                    array_car.add(each_car_details[0]);
                    write_car.add(each_car_details[0]);
                
                }

            }
            if(get_changes_item == 0){
                JOptionPane.showMessageDialog(this, "Not allowed to Change Car ID", "Error Message", JOptionPane.ERROR_MESSAGE);

            }
                else{
                if(action == 1){
                JOptionPane.showMessageDialog(this, "Car Serial Number Record Exists!", "Information Message", JOptionPane.INFORMATION_MESSAGE);
                update_btn.setEnabled(true);
                //Write new car details back into the car.txt (overwrite)
                Path write_output = Paths.get("Car.txt");
                for(int x = 0; x<write_car.size(); x++){
                    //System.out.println(write_car.get(x));
                    
                    Files.write(write_output, write_car);
                    
                }
                JOptionPane.showMessageDialog(this, "New Car Details Updated", "Information Message", JOptionPane.INFORMATION_MESSAGE);

            }else{
                JOptionPane.showMessageDialog(this, "Car Serial Number Not Found", "Error Message", JOptionPane.ERROR_MESSAGE);

            }
                
            }
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EditCar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EditCar.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            


    }//GEN-LAST:event_update_btnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        AdminClass admin_class = new AdminClass();
        admin_class.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void search_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_textfieldKeyTyped
        char key_entered = evt.getKeyChar();
        // only allow number and alphabetic character
        if(!(Character.isAlphabetic(key_entered)) && (!(Character.isDigit(key_entered)))){
            evt.consume();  
        }
    }//GEN-LAST:event_search_textfieldKeyTyped

    private void changes_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changes_textfieldKeyTyped
        char key_entered = evt.getKeyChar();
        
        if(!(Character.isAlphabetic(key_entered)) && (!(Character.isDigit(key_entered)))){
            evt.consume();  
        }
    }//GEN-LAST:event_changes_textfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField changes_textfield;
    private javax.swing.JComboBox<String> details_selection;
    private javax.swing.JLabel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField search_textfield;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
